### ISSUE TITLE
PersianTools: convertToTimeStamp - The input format must be yyyy/mm/dd hh:mm:ss

### ISSUE THREAD

**Issue by alivtar** [ali-master/persian-tools#321]
**Describe the bug**
Can not get around how to work with 'timeAgo' function

**To Reproduce**
1. Go to 'https://codesandbox.io/s/quizzical-nightingale-12i28u?file=/src/App.js'
2. See the error in 'console'

**Expected behavior**
The expected behavior of the 'timeAgo' function is to work when the input pattern is passed correctly.
Even examples in the doc don't work.

**Comment by mediv0** [comment]
The problem lies in node version ( i guess ! ) and  `Date().toLocaleString` function 

in the newer version of nodes ( tested with `20.3.0` ) it adds a comma after the Date value e.g: `۱۴۰۲/۰۵/۰۳, ۱۹:۰۷:۳۲`
but older versions like `16.14.2` will result in `۱۴۰۲/۰۵/۰۳ ۲۳:۳۴:۵۹`

that comma makes regex test fail and throw Error as you can see 

im working on it
